export interface GlossaryTerm {
  term: string
  desc: string
  category: string
}

export const POKER_TERMS: GlossaryTerm[] = [
  // ── 基本 ──
  { term: 'ブラインド', desc: '強制ベット。SB（スモールブラインド）とBB（ビッグブラインド）がある。', category: '基本' },
  { term: 'アンティ', desc: '全員が払う強制ベット。トーナメント後半などで導入される。', category: '基本' },
  { term: 'ポット', desc: 'そのハンドで賭けられたチップの総額。', category: '基本' },
  { term: 'スタック', desc: '手持ちのチップ総額。', category: '基本' },
  { term: 'ホールカード', desc: '各プレイヤーに配られる2枚の手札。', category: '基本' },
  { term: 'コミュニティカード', desc: 'テーブル中央に開かれる5枚の共有カード。', category: '基本' },
  { term: 'ボード', desc: 'コミュニティカードのこと。', category: '基本' },
  { term: 'マック', desc: '手札を見せずに捨てること。', category: '基本' },
  { term: 'ディーラー', desc: 'カードを配る役。ボタンが置かれる。', category: '基本' },
  { term: 'ヘッズアップ', desc: '2人だけの対戦。', category: '基本' },
  { term: 'マルチウェイ', desc: '3人以上がポットに参加している状態。', category: '基本' },
  { term: 'ポケット', desc: 'ホールカードのこと。「ポケットエース」など。', category: '基本' },

  // ── ポジション ──
  { term: 'ポジション', desc: 'テーブルでの席順。後ろのポジションほど有利（情報が多い）。', category: 'ポジション' },
  { term: 'UTG', desc: 'Under The Gun。BBの左、最初にアクションする最も不利なポジション。', category: 'ポジション' },
  { term: 'UTG+1', desc: 'UTGの左隣。アーリーポジション。', category: 'ポジション' },
  { term: 'MP', desc: 'ミドルポジション。UTGとCOの間。', category: 'ポジション' },
  { term: 'HJ', desc: 'ハイジャック。COの1つ右。', category: 'ポジション' },
  { term: 'CO', desc: 'カットオフ。ボタンの1つ右。2番目に有利なポジション。', category: 'ポジション' },
  { term: 'BTN', desc: 'ボタン。ディーラーポジション。ポストフロップで最後にアクションできる最も有利な席。', category: 'ポジション' },
  { term: 'SB', desc: 'スモールブラインド。BTNの左隣。', category: 'ポジション' },
  { term: 'BB', desc: 'ビッグブラインド。SBの左隣。', category: 'ポジション' },
  { term: 'アーリーポジション', desc: 'UTG〜UTG+1。情報が少なく不利な席。', category: 'ポジション' },
  { term: 'ミドルポジション', desc: 'MP〜HJ。中間の席。', category: 'ポジション' },
  { term: 'レイトポジション', desc: 'CO〜BTN。有利な席。', category: 'ポジション' },
  { term: 'インポジション', desc: '相手より後にアクションする有利な状態。', category: 'ポジション' },
  { term: 'アウトオブポジション', desc: '相手より先にアクションする不利な状態。OOPとも。', category: 'ポジション' },
  { term: 'OOP', desc: 'Out Of Position。アウトオブポジションの略。', category: 'ポジション' },
  { term: 'IP', desc: 'In Position。インポジションの略。', category: 'ポジション' },

  // ── アクション ──
  { term: 'フォールド', desc: '手札を捨ててそのハンドから降りる。', category: 'アクション' },
  { term: 'チェック', desc: 'ベットせずにパスする（誰もベットしていない場合のみ可能）。', category: 'アクション' },
  { term: 'コール', desc: '前のベットと同額を出す。', category: 'アクション' },
  { term: 'ベット', desc: 'チップを賭ける。', category: 'アクション' },
  { term: 'レイズ', desc: '前のベットに上乗せして賭ける。', category: 'アクション' },
  { term: 'リレイズ', desc: 'レイズに対してさらにレイズすること。', category: 'アクション' },
  { term: 'オールイン', desc: '手持ちのチップを全て賭ける。', category: 'アクション' },
  { term: 'リンプ', desc: 'プリフロップでBB額でコールすること。弱いプレイとされる。', category: 'アクション' },
  { term: 'リンプイン', desc: 'リンプと同義。', category: 'アクション' },
  { term: 'オープン', desc: 'そのラウンドで最初にベット/レイズすること。', category: 'アクション' },
  { term: 'オープンレイズ', desc: 'プリフロップで最初にレイズすること。', category: 'アクション' },
  { term: '3bet', desc: 'オープンレイズに対するリレイズ。', category: 'アクション' },
  { term: '4bet', desc: '3betに対するさらなるリレイズ。', category: 'アクション' },
  { term: '5bet', desc: '4betに対するさらなるリレイズ。通常オールイン。', category: 'アクション' },
  { term: 'コールドコール', desc: 'レイズをコールすること（自分がまだアクションしていない状態で）。', category: 'アクション' },
  { term: 'スクイーズ', desc: 'オープンレイズとコールがあった後に大きくリレイズすること。', category: 'アクション' },
  { term: 'コンティニュエーションベット', desc: 'Cbet。プリフロップでレイズした人がフロップでもベットすること。', category: 'アクション' },
  { term: 'Cbet', desc: 'コンティニュエーションベットの略。', category: 'アクション' },
  { term: 'ダブルバレル', desc: 'フロップとターンで連続してベットすること。', category: 'アクション' },
  { term: 'トリプルバレル', desc: 'フロップ・ターン・リバーで3回連続ベットすること。', category: 'アクション' },
  { term: 'チェックレイズ', desc: 'チェックした後、相手のベットに対してレイズすること。', category: 'アクション' },
  { term: 'ドンクベット', desc: 'プリフロップアグレッサーより先にベットすること。', category: 'アクション' },
  { term: 'プローブベット', desc: 'プリフロップアグレッサーがチェックした後にベットすること。', category: 'アクション' },
  { term: 'オーバーベット', desc: 'ポットより大きい額をベットすること。', category: 'アクション' },
  { term: 'ブロックベット', desc: '相手の大きなベットを防ぐための小さなベット。', category: 'アクション' },
  { term: 'ミニレイズ', desc: '最小額でレイズすること。', category: 'アクション' },
  { term: 'ジャム', desc: 'オールインすること。', category: 'アクション' },
  { term: 'シップイット', desc: 'オールインすること（スラング）。', category: 'アクション' },

  // ── 戦略 ──
  { term: 'ポットオッズ', desc: 'コール額に対するポットの比率。コールすべきかの判断材料。', category: '戦略' },
  { term: 'インプライドオッズ', desc: '将来のベッティングラウンドで得られる期待値を含めたオッズ。', category: '戦略' },
  { term: 'アウツ', desc: '自分のハンドを完成させるカードの枚数。', category: '戦略' },
  { term: 'エクイティ', desc: '現時点でポットを獲得する確率。', category: '戦略' },
  { term: 'フォールドエクイティ', desc: '相手をフォールドさせることで得られる期待値。', category: '戦略' },
  { term: 'EV', desc: 'Expected Value。期待値。', category: '戦略' },
  { term: '+EV', desc: 'プラス期待値。長期的に利益が出るプレイ。', category: '戦略' },
  { term: '-EV', desc: 'マイナス期待値。長期的に損失が出るプレイ。', category: '戦略' },
  { term: 'バリュー', desc: '勝っている時に相手からチップを引き出すベット。', category: '戦略' },
  { term: 'バリューベット', desc: '相手に悪いハンドでコールしてもらうためのベット。', category: '戦略' },
  { term: 'ブラフ', desc: '弱いハンドで強いふりをしてベット/レイズすること。', category: '戦略' },
  { term: 'ピュアブラフ', desc: '改善の見込みがほぼないハンドでのブラフ。', category: '戦略' },
  { term: 'セミブラフ', desc: 'まだ完成していないが改善の可能性があるハンドでブラフすること。', category: '戦略' },
  { term: 'ブラフキャッチ', desc: '相手のブラフを読んで弱めのハンドでコールすること。', category: '戦略' },
  { term: 'ヒーローコール', desc: '相手のブラフを読んで薄いハンドでコールすること。', category: '戦略' },
  { term: 'スロープレイ', desc: '強いハンドをチェックやコールで隠すプレイ。', category: '戦略' },
  { term: 'トラップ', desc: '強いハンドを隠して相手をはめること。', category: '戦略' },
  { term: 'GTO', desc: 'Game Theory Optimal。ゲーム理論に基づく最適戦略。', category: '戦略' },
  { term: 'エクスプロイト', desc: '相手の弱点を突くプレイ。GTOから外れた調整。', category: '戦略' },
  { term: 'レンジ', desc: '特定の状況で持ちうるハンドの範囲。', category: '戦略' },
  { term: 'ハンドレンジ', desc: 'レンジと同義。', category: '戦略' },
  { term: 'ポラライズ', desc: '強いハンドと弱いハンド（ブラフ）のみでベットするレンジ構成。', category: '戦略' },
  { term: 'リニア', desc: '強さの順にベットするレンジ構成。', category: '戦略' },
  { term: 'マージン', desc: '中程度の強さのハンド。', category: '戦略' },
  { term: 'ブロッカー', desc: '相手が特定のハンドを持つ確率を下げるカード。', category: '戦略' },
  { term: 'カードリムーバル', desc: 'ブロッカーの効果。', category: '戦略' },
  { term: 'ボードテクスチャ', desc: 'フロップの特徴（ウェット/ドライなど）。', category: '戦略' },
  { term: 'ウェットボード', desc: 'ドローが多いボード（例：8♥9♥T♣）。', category: '戦略' },
  { term: 'ドライボード', desc: 'ドローが少ないボード（例：K♠7♦2♣）。', category: '戦略' },
  { term: 'ペアボード', desc: 'ボードにペアがあるボード。', category: '戦略' },
  { term: 'モノトーン', desc: '同じスートが3枚以上あるボード。', category: '戦略' },
  { term: 'レインボー', desc: '全て違うスートのボード。', category: '戦略' },
  { term: 'フリーカード', desc: 'チェックで回って無料で見れるカード。', category: '戦略' },
  { term: 'シンバリュー', desc: '微妙に勝っている可能性で小さくベットすること。', category: '戦略' },
  { term: 'リバースインプライドオッズ', desc: '完成しても負ける可能性を考慮したマイナスのオッズ。', category: '戦略' },
  { term: 'オーバーペア', desc: 'ボードのどのカードより高いペア。', category: '戦略' },
  { term: 'トップペア', desc: 'ボードの最高カードとのペア。', category: '戦略' },
  { term: 'セカンドペア', desc: 'ボードの2番目に高いカードとのペア。', category: '戦略' },
  { term: 'ボトムペア', desc: 'ボードの最低カードとのペア。', category: '戦略' },
  { term: 'キッカー', desc: 'ペア等の役に付随する最高のサイドカード。', category: '戦略' },
  { term: 'アウトキック', desc: 'キッカーで勝っている状態。', category: '戦略' },
  { term: 'ドミネイト', desc: '片方のカードが同じで、もう片方のカードが負けている状態。', category: '戦略' },

  // ── ハンド ──
  { term: 'ナッツ', desc: 'その状況で可能な最強のハンド。', category: 'ハンド' },
  { term: 'セカンドナッツ', desc: '2番目に強いハンド。', category: 'ハンド' },
  { term: 'ドロー', desc: 'あと1枚でフラッシュやストレートが完成する状態。', category: 'ハンド' },
  { term: 'フラッシュドロー', desc: 'あと1枚でフラッシュが完成する状態。', category: 'ハンド' },
  { term: 'ストレートドロー', desc: 'あと1枚でストレートが完成する状態。', category: 'ハンド' },
  { term: 'オープンエンドストレートドロー', desc: '両端で完成するストレートドロー（8アウツ）。OESD。', category: 'ハンド' },
  { term: 'OESD', desc: 'オープンエンドストレートドローの略。', category: 'ハンド' },
  { term: 'ガットショット', desc: '真ん中1枚で完成するストレートドロー（4アウツ）。', category: 'ハンド' },
  { term: 'インサイドストレートドロー', desc: 'ガットショットの別名。', category: 'ハンド' },
  { term: 'バックドア', desc: 'ターンとリバー両方で必要なカードが来て完成するドロー。', category: 'ハンド' },
  { term: 'コンボドロー', desc: 'フラッシュドローとストレートドローの両方があるハンド。', category: 'ハンド' },
  { term: 'セット', desc: 'ポケットペアとボードで作るスリーカード。', category: 'ハンド' },
  { term: 'トリップス', desc: 'ボードのペアと手札で作るスリーカード。', category: 'ハンド' },
  { term: 'ボート', desc: 'フルハウスのこと。', category: 'ハンド' },
  { term: 'クワッズ', desc: 'フォーカードのこと。', category: 'ハンド' },
  { term: 'ホイール', desc: 'A-2-3-4-5のストレート。最弱のストレート。', category: 'ハンド' },
  { term: 'ブロードウェイ', desc: '10-J-Q-K-Aのストレート。最強のストレート。', category: 'ハンド' },
  { term: 'ブロードウェイカード', desc: '10以上のカード（10, J, Q, K, A）。', category: 'ハンド' },
  { term: 'スーテッド', desc: '同じスートの2枚。例：A♠K♠', category: 'ハンド' },
  { term: 'オフスーツ', desc: '違うスートの2枚。例：A♠K♥', category: 'ハンド' },
  { term: 'コネクター', desc: '連続した2枚。例：98, JT', category: 'ハンド' },
  { term: 'スーテッドコネクター', desc: '同じスートの連続した2枚。', category: 'ハンド' },
  { term: 'ギャップ', desc: '1つ飛ばしの2枚。例：97, T8', category: 'ハンド' },
  { term: 'エアー', desc: '全くのブラフハンド。何もない状態。', category: 'ハンド' },
  { term: 'モンスター', desc: '非常に強いハンド。', category: 'ハンド' },
  { term: 'クーラー', desc: '強いハンド同士がぶつかる不運な状況。', category: 'ハンド' },
  { term: 'バッドビート', desc: '有利な状況から逆転負けすること。', category: 'ハンド' },
  { term: 'サックアウト', desc: '不利な状況から逆転勝ちすること。', category: 'ハンド' },
  { term: 'リバーラット', desc: 'リバーで逆転する人（蔑称）。', category: 'ハンド' },
  { term: 'ラグ', desc: '弱いカード（2〜6くらい）。', category: 'ハンド' },

  // ── 役 ──
  { term: 'ハイカード', desc: '役なし。最も高いカードで勝負。', category: '役' },
  { term: 'ワンペア', desc: '2枚の同ランクの役。', category: '役' },
  { term: 'ツーペア', desc: '2枚ペア×2組の役。', category: '役' },
  { term: 'スリーカード', desc: '同じランク3枚の役。', category: '役' },
  { term: 'ストレート', desc: '5枚連続の役（スート不問）。', category: '役' },
  { term: 'フラッシュ', desc: '同じスート5枚の役。', category: '役' },
  { term: 'フルハウス', desc: '3枚＋2枚の同ランクの役。', category: '役' },
  { term: 'フォーカード', desc: '同じランク4枚の役。', category: '役' },
  { term: 'ストレートフラッシュ', desc: '同じスートの5枚連続の役。', category: '役' },
  { term: 'ロイヤルフラッシュ', desc: '同じスートのA-K-Q-J-10の役。最強。', category: '役' },

  // ── ラウンド ──
  { term: 'プリフロップ', desc: 'フロップが開かれる前のベッティングラウンド。', category: 'ラウンド' },
  { term: 'フロップ', desc: '最初の3枚のコミュニティカードが開かれるラウンド。', category: 'ラウンド' },
  { term: 'ターン', desc: '4枚目のコミュニティカードが開かれるラウンド。', category: 'ラウンド' },
  { term: 'リバー', desc: '5枚目（最後）のコミュニティカードが開かれるラウンド。', category: 'ラウンド' },
  { term: 'ショーダウン', desc: '残ったプレイヤーが手札を見せて勝者を決める。', category: 'ラウンド' },
  { term: 'ポストフロップ', desc: 'フロップ以降のラウンド全体を指す。', category: 'ラウンド' },
  { term: 'ストリート', desc: '各ベッティングラウンドのこと。', category: 'ラウンド' },

  // ── トーナメント ──
  { term: 'MTT', desc: 'Multi Table Tournament。複数テーブルのトーナメント。', category: 'トーナメント' },
  { term: 'SNG', desc: 'Sit and Go。参加者が揃い次第開始するトーナメント。', category: 'トーナメント' },
  { term: 'バブル', desc: '入賞ライン直前の状況。', category: 'トーナメント' },
  { term: 'インザマネー', desc: '入賞圏内に入ること。ITM。', category: 'トーナメント' },
  { term: 'ITM', desc: 'In The Money。入賞圏内。', category: 'トーナメント' },
  { term: 'ファイナルテーブル', desc: '最終卓。', category: 'トーナメント' },
  { term: 'FT', desc: 'Final Table。ファイナルテーブルの略。', category: 'トーナメント' },
  { term: 'チップリーダー', desc: 'その時点で最もチップを持っているプレイヤー。', category: 'トーナメント' },
  { term: 'ショートスタック', desc: 'チップが少ない状態。', category: 'トーナメント' },
  { term: 'ビッグスタック', desc: 'チップが多い状態。', category: 'トーナメント' },
  { term: 'アベレージ', desc: '平均スタック。', category: 'トーナメント' },
  { term: 'M値', desc: 'スタック ÷ (SB+BB+アンティ)。あと何周できるかの指標。', category: 'トーナメント' },
  { term: 'BB数', desc: 'スタックをBBで割った数。', category: 'トーナメント' },
  { term: 'ICM', desc: 'Independent Chip Model。チップ量と賞金期待値の関係。', category: 'トーナメント' },
  { term: 'バウンティ', desc: '他プレイヤーを脱落させると得られる賞金。', category: 'トーナメント' },
  { term: 'ノックアウト', desc: '他プレイヤーを脱落させること。', category: 'トーナメント' },
  { term: 'リエントリー', desc: 'トーナメントで飛んだ後、再度参加すること（許可されている場合）。', category: 'トーナメント' },
  { term: 'リバイ', desc: 'プレミアリングでチップを追加購入すること。', category: 'トーナメント' },
  { term: 'アドオン', desc: 'リバイ期間終了時に追加チップを購入すること。', category: 'トーナメント' },
  { term: 'レイトレジ', desc: 'トーナメント開始後に参加すること。', category: 'トーナメント' },
  { term: 'ブラインドアップ', desc: 'ブラインドが上がること。', category: 'トーナメント' },
  { term: 'レベル', desc: 'ブラインドの段階。', category: 'トーナメント' },
  { term: 'バスト', desc: 'チップがなくなって脱落すること。', category: 'トーナメント' },
  { term: 'オールインエクイティ', desc: 'オールイン時の勝率。', category: 'トーナメント' },
  { term: 'プッシュフォールド', desc: 'ショートスタックでオールインかフォールドかの2択戦略。', category: 'トーナメント' },

  // ── プレイヤータイプ ──
  { term: 'タイト', desc: 'ハンド選択が厳しく、良いハンドのみでプレイするスタイル。', category: 'プレイヤー' },
  { term: 'ルース', desc: '多くのハンドでプレイする緩いスタイル。', category: 'プレイヤー' },
  { term: 'アグレッシブ', desc: 'ベット・レイズを多用する攻撃的なスタイル。', category: 'プレイヤー' },
  { term: 'パッシブ', desc: 'チェック・コールを多用する受動的なスタイル。', category: 'プレイヤー' },
  { term: 'TAG', desc: 'Tight Aggressive。タイトかつアグレッシブ。理想的とされる。', category: 'プレイヤー' },
  { term: 'LAG', desc: 'Loose Aggressive。ルースかつアグレッシブ。', category: 'プレイヤー' },
  { term: 'ニット', desc: '極端にタイトなプレイヤー。', category: 'プレイヤー' },
  { term: 'マニアック', desc: '極端にアグレッシブなプレイヤー。', category: 'プレイヤー' },
  { term: 'コーリングステーション', desc: 'なんでもコールするプレイヤー。', category: 'プレイヤー' },
  { term: 'フィッシュ', desc: '弱いプレイヤー。カモ。', category: 'プレイヤー' },
  { term: 'ドンク', desc: '下手なプレイヤー（蔑称）。', category: 'プレイヤー' },
  { term: 'シャーク', desc: '強いプレイヤー。', category: 'プレイヤー' },
  { term: 'レギュラー', desc: '常連の強いプレイヤー。レグ。', category: 'プレイヤー' },
  { term: 'レグ', desc: 'レギュラーの略。', category: 'プレイヤー' },
  { term: 'レクリエーショナル', desc: '趣味でプレイするカジュアルプレイヤー。', category: 'プレイヤー' },

  // ── 心理・その他 ──
  { term: 'ティルト', desc: '感情的になってプレイが乱れている状態。', category: '心理' },
  { term: 'スチーム', desc: 'ティルトしている状態。', category: '心理' },
  { term: 'テル', desc: '相手のハンドの強さを示す無意識の仕草や傾向。', category: '心理' },
  { term: 'リバースTテル', desc: '意図的に逆のテルを出すこと。', category: '心理' },
  { term: 'レベル', desc: '思考の深さ。「相手は何を考えているか」を何段階先まで読むか。', category: '心理' },
  { term: 'メタゲーム', desc: 'ゲーム外での駆け引きや、過去のプレイ履歴を利用した戦略。', category: '心理' },
  { term: 'イメージ', desc: '他プレイヤーから見た自分の印象。', category: '心理' },
  { term: 'アジャスト', desc: '相手や状況に合わせてプレイを調整すること。', category: '心理' },
  { term: 'エクスプロイティブ', desc: '相手の弱点を突くプレイスタイル。', category: '心理' },
  { term: 'バランス', desc: 'ブラフとバリューの比率を適切に保つこと。', category: '心理' },
  { term: 'マージナル', desc: '判断が難しい微妙な状況。', category: '心理' },
  { term: 'スポット', desc: '特定のシチュエーション。', category: '心理' },
  { term: 'ライブリード', desc: 'ライブゲーム中に相手のテルを読むこと。', category: '心理' },

  // ── スート ──
  { term: 'スペード', desc: '♠ スート。最も強いとされることが多い。', category: 'スート' },
  { term: 'ハート', desc: '♥ スート。', category: 'スート' },
  { term: 'ダイヤ', desc: '♦ スート。', category: 'スート' },
  { term: 'クラブ', desc: '♣ スート。', category: 'スート' },
  { term: 'スート', desc: 'カードのマーク（♠♥♦♣）。', category: 'スート' },

  // ── ツール・用語 ──
  { term: 'HUD', desc: 'Heads-Up Display。相手のスタッツを表示するツール。', category: 'ツール' },
  { term: 'スタッツ', desc: 'プレイの統計データ。', category: 'ツール' },
  { term: 'VPIP', desc: 'Voluntarily Put $ In Pot。自発的にポットに参加した割合。', category: 'ツール' },
  { term: 'PFR', desc: 'Pre-Flop Raise。プリフロップでレイズした割合。', category: 'ツール' },
  { term: 'AF', desc: 'Aggression Factor。アグレッション指標。', category: 'ツール' },
  { term: 'WTSD', desc: 'Went To Showdown。ショーダウンまで行った割合。', category: 'ツール' },
  { term: 'W$SD', desc: 'Won $ at Showdown。ショーダウンで勝った割合。', category: 'ツール' },
  { term: 'ソルバー', desc: 'GTO戦略を計算するツール。', category: 'ツール' },
  { term: 'エクイティ計算機', desc: 'ハンド同士の勝率を計算するツール。', category: 'ツール' },
  { term: 'ハンドヒストリー', desc: '過去のプレイ記録。', category: 'ツール' },
  { term: 'リプレイ', desc: '過去のハンドを再検証すること。', category: 'ツール' },
  { term: 'ハンドレビュー', desc: 'プレイを振り返って分析すること。', category: 'ツール' },
]

export const GLOSSARY_TERM_NAMES = POKER_TERMS.map(t => t.term)
